vars:
  - wdir: .
  - env: dev
  - model_type: matrix

stages:
  covisitation:
    wdir: ${wdir}
    cmd: >-
      python src/covisitation_matrix.py
    deps:
      - src/covisitation_matrix.py
    params:
      - params.yaml:
  evaluate:
    wdir: ${wdir}
    cmd: >-
      python src/evaluate.py
    deps:
      - src/evaluate.py
    metrics:
      - metrics/scores.json:
          cache: false