vars:
  - wdir: .
  - env: dev
  - model_type: matrix
  - config/settings.yaml:metrics

stages:
  covisitation:
    wdir: ${wdir}
    cmd: >-
      python src/covisitation_matrix.py
    deps:
      - src/covisitation_matrix.
      - data/processed_data/train_sessions.parquet
      - data/processed_data/test_sessions.parquet
    params:
      - params.yaml:
  evaluate:
    wdir: ${wdir}
    cmd: >-
      python src/evaluate.py
    deps:
      - src/evaluate.py
    metrics:
      - ${metrics.path}