vars:
  - wdir: .
  - env: dev
  - model_type: matrix
  - config/settings.yaml:metrics

stages:
  covisitation:
    wdir: ${wdir}
    cmd: >-
      pipenv run python -m src.covisitation_matrix
    deps:
      - src/covisitation_matrix.py
    params:
      - config/params.yaml:
    metrics:
      - ${metrics.path}