general:
  timestamp_format: "%Y%m%d.%H%M%S"
  project_path: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/
paths:
  raw: ${project_path} + data/raw/
  processed: ${project_path} + data/processed_data/
  data_split: ${project_path} + data/data_splits/

session_files:
  train: ${project_path} + data/data_splits/train_sessions.jsonl
  test: ${project_path} + data/data_splits/test_sessions.jsonl
  test_full: ${project_path} + data/data_splits/test_sessions_full.jsonl
  test_labels: ${project_path} + data/data_splits/test_labels.jsonl

processed_files:
  train: ${project_path} + data/processed_data/train_sessions.parquet
  test: ${project_path} + data/processed_data/test_sessions.parquet

predictions:
  path: ${project_path} + data/predictions/predictions.csv

metrics:
  path: ${project_path} + metrics/scores.json
