vars:
  - project_path: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/
general:
  timestamp_format: "%Y%m%d.%H%M%S"

paths:
  raw: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/raw/
  processed: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/processed_data/
  data_split: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/data_splits/

session_files:
  train: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/data_splits/train_sessions.jsonl
  test: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/data_splits/test_sessions.jsonl
  test_full: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/data_splits/test_sessions_full.jsonl
  test_labels: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/data_splits/test_labels.jsonl

processed_files:
  train: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/processed_data/train_sessions.parquet
  test: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/processed_data/test_sessions.parquet

predictions:
  path: /Users/sandeep.kothiwale/github/kaggle/recsys-dataset/data/predictions/predictions.csv
